server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置dashboard地址
        dashboard: localhost:8080
        # 默认8710端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      datasource:
        dsl:
          nacos:
            server-addr: locolhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'