server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zoujidi
    password: zoujidi1234
    #空闲的时候进行检测是开启的，但是检测的查询语句没有设置。大致意思就是说，当数据库没有接收到请求时，会进行数据库连接检测，检查数据库是否还是连着的。检查数据库是否断开需要发送sql语句。
    druid:
      test-while-idle: true
      validation-query: select 1

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8001
    #访问路径可以显示ip
    prefer-ip-address: true
    #eureka客户端向服务器端发送心跳的时间间隔，单位为秒(默认30s)
    # lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳等待时间上线，单位为秒（默认是90s），超时将剔除服务
    # lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.zoujidi.springcloud.entity  #所有entity别名所在包

