server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**  #断言，路径相匹配的进行路由
            # - After=2020-08-04T16:28:49.332+08:00[Asia/Shanghai]
            # - Cookie=username,zoujidi
            - Header=X-Request-Id, \d+ #要求请求头要有X-Request-Id属性并且值为整数的正则表达式
          filter:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id值为1024

        - id: payment_routh2 #路由的id，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

